name: sonarr
description: Facilitate the communication to and from Sonarr's API, a smart PVR for newsgroup and bittorrent users.
version: 1.1.1
homepage: https://github.com/CometTools/Dart-Packages/tree/master/sonarr
repository: https://github.com/CometTools/Dart-Packages
issue_tracker: https://github.com/CometTools/Dart-Packages/issues
environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  dio: ^3.0.10
  intl: ^0.17.0
  json_annotation: ^3.1.0
  meta: ^1.2.3
dev_dependencies:
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  test: ^1.15.4
scripts:
  build: pub run build_runner build --delete-conflicting-outputs
