name: overseerr
description: Facilitate the communication to and from Overseerr's API, a request management and media discovery tool for the Plex ecosystem
version: 0.0.1-pre.3
homepage: https://github.com/CometTools/Dart-Packages/tree/master/overseerr
repository: https://github.com/CometTools/Dart-Packages
issue_tracker: https://github.com/CometTools/Dart-Packages/issues
environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  dio: ^3.0.10
  json_annotation: ^4.0.0
  meta: ^1.3.0
dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  test: ^1.16.5
scripts:
  build: pub run build_runner build --delete-conflicting-outputs
