name: wake_on_lan
description: Send wake on LAN magic packets to devices on your local network.
version: 1.1.2+1
homepage: https://github.com/CometTools/Dart-Packages/tree/master/wake_on_lan
repository: https://github.com/CometTools/Dart-Packages
issue_tracker: https://github.com/CometTools/Dart-Packages/issues
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  convert: ^3.0.0
dev_dependencies:
  test: ^1.16.5
scripts:
  coverage: test_coverage --no-badge
  netcat: nc -ul 9 | hexdump -C
