name: tautulli
description: Facilitate the communication to and from Tautulli's API, a Python based monitoring and tracking tool for Plex Media Server.
version: 0.0.1-pre.5
homepage: https://github.com/CometTools/Packages
repository: https://github.com/CometTools/Packages/tree/master/packages/tautulli
issue_tracker: https://github.com/CometTools/Packages/issues
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  dio: ^3.0.9
  json_serializable: ^3.3.0
  meta: ^1.1.8
dev_dependencies:
  test: ^1.15.1
scripts:
  tests: dart pub run test test
  coverage: test_coverage --no-badge
