name: tautulli
on:
  push:
    branches: [ master ]
    paths:
      - "packages/tautulli/**"
  pull_request:
    branches: [ master ]
    paths:
      - "packages/tautulli/**"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'packages/tautulli'
    container:
      image: google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: pub get
    - name: Run Tests
      run: pub run test
    - name: Collect Coverage
      run: |
        pub global activate test_coverage
        pub global run test_coverage --no-badge
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        file: packages/tautulli/coverage/lcov.info
        flags: tautulli
